repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/crate-ci/typos
    rev: v1.46.0
    hooks:
      - id: typos

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:

      - id: ruff-check
        files: ^(skore/(hatch|src|tests))|(examples)/
        args: [--fix, --extend-select, I]

      - id: ruff-format
        files: ^(skore/(hatch|src|tests))|(examples)/

  - repo: local
    hooks:

      - id: mypy
        name: mypy
        entry: mypy --config-file=skore/pyproject.toml skore/
        language: unsupported
        pass_filenames: false
        files: ^skore/

      - id: no-redundant-underscore
        name: check for redundant leading underscores
        entry: |
          python -c "
          import sys
          from pathlib import Path

          redundant = [
            str(p) for p in map(Path, sys.argv[1:])
            if p.name.startswith('_') and not p.name.startswith('__')
            and any(d.startswith('_') for d in p.parent.parts)
          ]

          if redundant:
            print('Offending file paths:')
            print('\n'.join(redundant))
            sys.exit(1)
          "
        language: unsupported
        pass_filenames: true
        files: ^skore/src/.*\.py$
