from __future__ import annotations

from numpy.testing import assert_almost_equal
from pydantic import ValidationError
from pytest import mark, param, raises

from skore_hub_project.metric import (
    AccuracyTest,
    AccuracyTestMean,
    AccuracyTestStd,
    AccuracyTrain,
    AccuracyTrainMean,
    AccuracyTrainStd,
    BrierScoreTest,
    BrierScoreTestMean,
    BrierScoreTestStd,
    BrierScoreTrain,
    BrierScoreTrainMean,
    BrierScoreTrainStd,
    LogLossTest,
    LogLossTestMean,
    LogLossTestStd,
    LogLossTrain,
    LogLossTrainMean,
    LogLossTrainStd,
    PrecisionTest,
    PrecisionTestMean,
    PrecisionTestStd,
    PrecisionTrain,
    PrecisionTrainMean,
    PrecisionTrainStd,
    R2Test,
    R2TestMean,
    R2TestStd,
    R2Train,
    R2TrainMean,
    R2TrainStd,
    RecallTest,
    RecallTestMean,
    RecallTestStd,
    RecallTrain,
    RecallTrainMean,
    RecallTrainStd,
    RmseTest,
    RmseTestMean,
    RmseTestStd,
    RmseTrain,
    RmseTrainMean,
    RmseTrainStd,
    RocAucTest,
    RocAucTestMean,
    RocAucTestStd,
    RocAucTrain,
    RocAucTrainMean,
    RocAucTrainStd,
)


@mark.parametrize(
    "report,Metric,accessor,name,verbose_name,greater_is_better,data_source,position,value",
    (
        param(
            "binary_classification",
            AccuracyTrain,
            "accuracy",
            "accuracy",
            "Accuracy",
            True,
            "train",
            None,
            1.0,
            id="AccuracyTrain",
        ),
        param(
            "binary_classification",
            AccuracyTest,
            "accuracy",
            "accuracy",
            "Accuracy",
            True,
            "test",
            None,
            0.9,
            id="AccuracyTest",
        ),
        param(
            "cv_binary_classification",
            AccuracyTrainMean,
            "accuracy",
            "accuracy_mean",
            "Accuracy - MEAN",
            True,
            "train",
            None,
            1.0,
            id="AccuracyTrainMean",
        ),
        param(
            "cv_binary_classification",
            AccuracyTestMean,
            "accuracy",
            "accuracy_mean",
            "Accuracy - MEAN",
            True,
            "test",
            None,
            0.93,
            id="AccuracyTestMean",
        ),
        param(
            "cv_binary_classification",
            AccuracyTrainStd,
            "accuracy",
            "accuracy_std",
            "Accuracy - STD",
            False,
            "train",
            None,
            0.0,
            id="AccuracyTrainStd",
        ),
        param(
            "cv_binary_classification",
            AccuracyTestStd,
            "accuracy",
            "accuracy_std",
            "Accuracy - STD",
            False,
            "test",
            None,
            0.04472135954999579,
            id="AccuracyTestStd",
        ),
        param(
            "binary_classification",
            BrierScoreTrain,
            "brier_score",
            "brier_score",
            "Brier score",
            False,
            "train",
            None,
            0.007277500000000001,
            id="BrierScoreTrain",
        ),
        param(
            "binary_classification",
            BrierScoreTest,
            "brier_score",
            "brier_score",
            "Brier score",
            False,
            "test",
            None,
            0.09025999999999999,
            id="BrierScoreTest",
        ),
        param(
            "cv_binary_classification",
            BrierScoreTrainMean,
            "brier_score",
            "brier_score_mean",
            "Brier score - MEAN",
            False,
            "train",
            None,
            0.008439499999999999,
            id="BrierScoreTrainMean",
        ),
        param(
            "cv_binary_classification",
            BrierScoreTestMean,
            "brier_score",
            "brier_score_mean",
            "Brier score - MEAN",
            False,
            "test",
            None,
            0.060865999999999996,
            id="BrierScoreTestMean",
        ),
        param(
            "cv_binary_classification",
            BrierScoreTrainStd,
            "brier_score",
            "brier_score_std",
            "Brier score - STD",
            False,
            "train",
            None,
            0.0004868365678027891,
            id="BrierScoreTrainStd",
        ),
        param(
            "cv_binary_classification",
            BrierScoreTestStd,
            "brier_score",
            "brier_score_std",
            "Brier score - STD",
            False,
            "test",
            None,
            0.015918303694175455,
            id="BrierScoreTestStd",
        ),
        param(
            "binary_classification",
            LogLossTrain,
            "log_loss",
            "log_loss",
            "Log loss",
            False,
            "train",
            4,
            0.06911280690412243,
            id="LogLossTrain",
        ),
        param(
            "binary_classification",
            LogLossTest,
            "log_loss",
            "log_loss",
            "Log loss",
            False,
            "test",
            4,
            0.3168690248138036,
            id="LogLossTest",
        ),
        param(
            "cv_binary_classification",
            LogLossTrainMean,
            "log_loss",
            "log_loss_mean",
            "Log loss - MEAN",
            False,
            "train",
            4,
            0.07706302057996325,
            id="LogLossTrainMean",
        ),
        param(
            "cv_binary_classification",
            LogLossTestMean,
            "log_loss",
            "log_loss_mean",
            "Log loss - MEAN",
            False,
            "test",
            4,
            0.23938382759923754,
            id="LogLossTestMean",
        ),
        param(
            "cv_binary_classification",
            LogLossTrainStd,
            "log_loss",
            "log_loss_std",
            "Log loss - STD",
            False,
            "train",
            None,
            0.003611541148136149,
            id="LogLossTrainStd",
        ),
        param(
            "cv_binary_classification",
            LogLossTestStd,
            "log_loss",
            "log_loss_std",
            "Log loss - STD",
            False,
            "test",
            None,
            0.030545861791452432,
            id="LogLossTestStd",
        ),
        param(
            "binary_classification",
            PrecisionTrain,
            "precision",
            "precision",
            "Precision (macro)",
            True,
            "train",
            None,
            1.0,
            id="PrecisionTrain",
        ),
        param(
            "binary_classification",
            PrecisionTest,
            "precision",
            "precision",
            "Precision (macro)",
            True,
            "test",
            None,
            0.8888888888888888,
            id="PrecisionTest",
        ),
        param(
            "cv_binary_classification",
            PrecisionTrainMean,
            "precision",
            "precision_mean",
            "Precision (macro) - MEAN",
            True,
            "train",
            None,
            1.0,
            id="PrecisionTrainMean",
        ),
        param(
            "cv_binary_classification",
            PrecisionTestMean,
            "precision",
            "precision_mean",
            "Precision (macro) - MEAN",
            True,
            "test",
            None,
            0.9343434343434345,
            id="PrecisionTestMean",
        ),
        param(
            "cv_binary_classification",
            PrecisionTrainStd,
            "precision",
            "precision_std",
            "Precision (macro) - STD",
            False,
            "train",
            None,
            0.0,
            id="PrecisionTrainStd",
        ),
        param(
            "cv_binary_classification",
            PrecisionTestStd,
            "precision",
            "precision_std",
            "Precision (macro) - STD",
            False,
            "test",
            None,
            0.045173090454541195,
            id="PrecisionTestStd",
        ),
        param(
            "regression",
            R2Train,
            "r2",
            "r2",
            "R²",
            True,
            "train",
            None,
            0.9997075936149707,
            id="R2Train",
        ),
        param(
            "regression",
            R2Test,
            "r2",
            "r2",
            "R²",
            True,
            "test",
            None,
            0.6757085221095596,
            id="R2Test",
        ),
        param(
            "cv_regression",
            R2TrainMean,
            "r2",
            "r2_mean",
            "R² - MEAN",
            True,
            "train",
            None,
            0.9996757990105992,
            id="R2TrainMean",
        ),
        param(
            "cv_regression",
            R2TestMean,
            "r2",
            "r2_mean",
            "R² - MEAN",
            True,
            "test",
            None,
            0.7999871077321583,
            id="R2TestMean",
        ),
        param(
            "cv_regression",
            R2TrainStd,
            "r2",
            "r2_std",
            "R² - STD",
            False,
            "train",
            None,
            4.8687384179271224e-05,
            id="R2TrainStd",
        ),
        param(
            "cv_regression",
            R2TestStd,
            "r2",
            "r2_std",
            "R² - STD",
            False,
            "test",
            None,
            0.0528129534702117,
            id="R2TestStd",
        ),
        param(
            "binary_classification",
            RecallTrain,
            "recall",
            "recall",
            "Recall (macro)",
            True,
            "train",
            None,
            1.0,
            id="RecallTrain",
        ),
        param(
            "binary_classification",
            RecallTest,
            "recall",
            "recall",
            "Recall (macro)",
            True,
            "test",
            None,
            0.9230769230769231,
            id="RecallTest",
        ),
        param(
            "cv_binary_classification",
            RecallTrainMean,
            "recall",
            "recall_mean",
            "Recall (macro) - MEAN",
            True,
            "train",
            None,
            1.0,
            id="RecallTrainMean",
        ),
        param(
            "cv_binary_classification",
            RecallTestMean,
            "recall",
            "recall_mean",
            "Recall (macro) - MEAN",
            True,
            "test",
            None,
            0.93,
            id="RecallTestMean",
        ),
        param(
            "cv_binary_classification",
            RecallTrainStd,
            "recall",
            "recall_std",
            "Recall (macro) - STD",
            False,
            "train",
            None,
            0.0,
            id="RecallTrainStd",
        ),
        param(
            "cv_binary_classification",
            RecallTestStd,
            "recall",
            "recall_std",
            "Recall (macro) - STD",
            False,
            "test",
            None,
            0.04472135954999573,
            id="RecallTestStd",
        ),
        param(
            "regression",
            RmseTrain,
            "rmse",
            "rmse",
            "RMSE",
            False,
            "train",
            3,
            2.4355616448506994,
            id="RmseTrain",
        ),
        param(
            "regression",
            RmseTest,
            "rmse",
            "rmse",
            "RMSE",
            False,
            "test",
            3,
            73.15561429220227,
            id="RmseTest",
        ),
        param(
            "cv_regression",
            RmseTrainMean,
            "rmse",
            "rmse_mean",
            "RMSE - MEAN",
            False,
            "train",
            3,
            2.517350366068551,
            id="RmseTrainMean",
        ),
        param(
            "cv_regression",
            RmseTestMean,
            "rmse",
            "rmse_mean",
            "RMSE - MEAN",
            False,
            "test",
            3,
            61.4227542951946,
            id="RmseTestMean",
        ),
        param(
            "cv_regression",
            RmseTrainStd,
            "rmse",
            "rmse_std",
            "RMSE - STD",
            False,
            "train",
            None,
            0.19476154817956934,
            id="RmseTrainStd",
        ),
        param(
            "cv_regression",
            RmseTestStd,
            "rmse",
            "rmse_std",
            "RMSE - STD",
            False,
            "test",
            None,
            12.103352184447452,
            id="RmseTestStd",
        ),
        param(
            "binary_classification",
            RocAucTrain,
            "roc_auc",
            "roc_auc",
            "ROC AUC",
            True,
            "train",
            3,
            1.0,
            id="RocAucTrain",
        ),
        param(
            "binary_classification",
            RocAucTest,
            "roc_auc",
            "roc_auc",
            "ROC AUC",
            True,
            "test",
            3,
            0.989010989010989,
            id="RocAucTest",
        ),
        param(
            "cv_binary_classification",
            RocAucTrainMean,
            "roc_auc",
            "roc_auc_mean",
            "ROC AUC - MEAN",
            True,
            "train",
            3,
            1.0,
            id="RocAucTrainMean",
        ),
        param(
            "cv_binary_classification",
            RocAucTestMean,
            "roc_auc",
            "roc_auc_mean",
            "ROC AUC - MEAN",
            True,
            "test",
            3,
            0.986,
            id="RocAucTestMean",
        ),
        param(
            "cv_binary_classification",
            RocAucTrainStd,
            "roc_auc",
            "roc_auc_std",
            "ROC AUC - STD",
            False,
            "train",
            None,
            5.551115123125783e-17,
            id="RocAucTrainStd",
        ),
        param(
            "cv_binary_classification",
            RocAucTestStd,
            "roc_auc",
            "roc_auc_std",
            "ROC AUC - STD",
            False,
            "test",
            None,
            0.015165750888103078,
            id="RocAucTestStd",
        ),
    ),
)
class TestMetric:
    def test_metric_available_accessor(
        self,
        monkeypatch,
        report,
        Metric,
        accessor,
        name,
        verbose_name,
        greater_is_better,
        data_source,
        position,
        value,
        request,
    ):
        report = request.getfixturevalue(report)

        # available accessor
        metric = Metric(report=report)
        metric.compute()

        metric_payload = metric.model_dump()

        assert_almost_equal(metric_payload.pop("value"), value)
        assert metric_payload == {
            "name": name,
            "verbose_name": verbose_name,
            "greater_is_better": greater_is_better,
            "data_source": data_source,
            "position": position,
        }

    def test_metric_unavailable_accessor(
        self,
        monkeypatch,
        report,
        Metric,
        accessor,
        name,
        verbose_name,
        greater_is_better,
        data_source,
        position,
        value,
        request,
    ):
        report = request.getfixturevalue(report)

        # unavailable accessor
        monkeypatch.delattr(report.metrics.__class__, accessor)

        metric = Metric(report=report)
        metric.compute()

        metric_payload = metric.model_dump()

        assert metric_payload == {
            "name": name,
            "verbose_name": verbose_name,
            "greater_is_better": greater_is_better,
            "data_source": data_source,
            "position": position,
            "value": None,
        }

    def test_metric_exception(
        self,
        monkeypatch,
        report,
        Metric,
        accessor,
        name,
        verbose_name,
        greater_is_better,
        data_source,
        position,
        value,
        request,
    ):
        report = request.getfixturevalue(report)

        # wrong type
        with raises(
            ValidationError,
            match=f"Input should be an instance of {report.__class__.__name__}",
        ):
            Metric(report=None)
