name: Blank issue
description: Any kind of issue that doesn't fit the other templates.
labels: ['needs-triage', 'user-reported']

body:
- type: textarea
  attributes:
    label: "What would you like to say?"
