name: Deploy sphinx documentation

inputs:
  CONFIGURATION:
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y rclone
    - shell: bash
      run: echo "${{ inputs.CONFIGURATION }}" > rclone.configuration
    - shell: bash
      run: |
        rclone --config rclone.configuration \
               sync \
               sphinx/build/html/ \
               scaleway:prod-probabl-skore/doc/latest/
