name: Deploy sphinx documentation
permissions:
  contents: write
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        rm -rf docs/latest
        mv sphinx/build/html docs/latest
    - shell: bash
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'

        git add docs/latest
        git commit -m 'docs: Build documentation triggered by ${{ github.sha }}'
        git push
