from pydantic import ValidationError
from pytest import mark, param, raises

from skore._plugins.hub.artifact.media import (
    ConfusionMatrixDataFrameTest,
    ConfusionMatrixDataFrameTrain,
    PrecisionRecallDataFrameTest,
    PrecisionRecallDataFrameTrain,
    PredictionErrorDataFrameTest,
    PredictionErrorDataFrameTrain,
    RocDataFrameTest,
    RocDataFrameTrain,
)
from skore._plugins.hub.artifact.media.performance import PerformanceDataFrame
from skore._plugins.hub.artifact.serializer import Serializer
from skore._plugins.hub.json import dumps


def serialize_dataframe(display) -> bytes:
    frame = display.frame(**PerformanceDataFrame.get_frame_kwargs(display))

    return dumps(
        frame.astype(object).where(frame.notna(), "NaN").to_dict(orient="tight")
    )


@mark.filterwarnings(
    # ignore deprecation warnings generated by the way `pandas` is used by `seaborn`
    # and `skore`
    "ignore:The default of observed=False is deprecated.*:FutureWarning",
)
@mark.parametrize(
    "Media,report,accessor,data_source,content_type,serialize",
    (
        param(
            PrecisionRecallDataFrameTest,
            "binary_classification",
            "precision_recall",
            "test",
            "application/vnd.dataframe",
            serialize_dataframe,
            id="PrecisionRecallDataFrameTest[estimator]",
        ),
        param(
            PrecisionRecallDataFrameTrain,
            "binary_classification",
            "precision_recall",
            "train",
            "application/vnd.dataframe",
            serialize_dataframe,
            id="PrecisionRecallDataFrameTrain[estimator]",
        ),
        param(
            PrecisionRecallDataFrameTest,
            "cv_binary_classification",
            "precision_recall",
            "test",
            "application/vnd.dataframe",
            serialize_dataframe,
            id="PrecisionRecallDataFrameTest[cross-validation]",
        ),
        param(
            PrecisionRecallDataFrameTrain,
            "cv_binary_classification",
            "precision_recall",
            "train",
            "application/vnd.dataframe",
            serialize_dataframe,
            id="PrecisionRecallDataFrameTrain[cross-validation]",
        ),
        param(
            PredictionErrorDataFrameTest,
            "regression",
            "prediction_error",
            "test",
            "application/vnd.dataframe",
            serialize_dataframe,
            id="PredictionErrorDataFrameTest[estimator]",
        ),
        param(
            PredictionErrorDataFrameTrain,
            "regression",
            "prediction_error",
            "train",
            "application/vnd.dataframe",
            serialize_dataframe,
            id="PredictionErrorDataFrameTrain[estimator]",
        ),
        param(
            PredictionErrorDataFrameTest,
            "cv_regression",
            "prediction_error",
            "test",
            "application/vnd.dataframe",
            serialize_dataframe,
            id="PredictionErrorDataFrameTest[cross-validation]",
        ),
        param(
            PredictionErrorDataFrameTrain,
            "cv_regression",
            "prediction_error",
            "train",
            "application/vnd.dataframe",
            serialize_dataframe,
            id="PredictionErrorDataFrameTrain[cross-validation]",
        ),
        param(
            RocDataFrameTest,
            "binary_classification",
            "roc",
            "test",
            "application/vnd.dataframe",
            serialize_dataframe,
            id="RocDataFrameTest[estimator]",
        ),
        param(
            RocDataFrameTrain,
            "binary_classification",
            "roc",
            "train",
            "application/vnd.dataframe",
            serialize_dataframe,
            id="RocDataFrameTrain[estimator]",
        ),
        param(
            RocDataFrameTest,
            "cv_binary_classification",
            "roc",
            "test",
            "application/vnd.dataframe",
            serialize_dataframe,
            id="RocDataFrameTest[cross-validation]",
        ),
        param(
            RocDataFrameTrain,
            "cv_binary_classification",
            "roc",
            "train",
            "application/vnd.dataframe",
            serialize_dataframe,
            id="RocDataFrameTrain[cross-validation]",
        ),
        param(
            ConfusionMatrixDataFrameTest,
            "binary_classification",
            "confusion_matrix",
            "test",
            "application/vnd.dataframe",
            serialize_dataframe,
            id="ConfusionMatrixDataFrameTest[estimator]",
        ),
        param(
            ConfusionMatrixDataFrameTrain,
            "binary_classification",
            "confusion_matrix",
            "train",
            "application/vnd.dataframe",
            serialize_dataframe,
            id="ConfusionMatrixDataFrameTrain[estimator]",
        ),
        param(
            ConfusionMatrixDataFrameTest,
            "cv_binary_classification",
            "confusion_matrix",
            "test",
            "application/vnd.dataframe",
            serialize_dataframe,
            id="ConfusionMatrixDataFrameTest[cross-validation]",
        ),
        param(
            ConfusionMatrixDataFrameTrain,
            "cv_binary_classification",
            "confusion_matrix",
            "train",
            "application/vnd.dataframe",
            serialize_dataframe,
            id="ConfusionMatrixDataFrameTrain[cross-validation]",
        ),
    ),
)
@mark.respx()
def test_performance(
    monkeypatch,
    Media,
    report,
    accessor,
    data_source,
    content_type,
    serialize,
    upload_mock,
    request,
    project,
):
    report = request.getfixturevalue(report)
    display = getattr(report.metrics, accessor)(data_source=data_source)
    content = serialize(display)

    with Serializer(content) as serializer:
        checksum = serializer.checksum

    # available accessor
    assert Media(project=project, report=report).model_dump() == {
        "content_type": content_type,
        "name": accessor,
        "data_source": data_source,
        "checksum": checksum,
    }

    # ensure `upload` is well called
    assert upload_mock.called
    assert not upload_mock.call_args.args
    assert upload_mock.call_args.kwargs == {
        "project": project,
        "content": content,
        "content_type": content_type,
    }

    # unavailable accessor
    monkeypatch.delattr(report.metrics.__class__, accessor)
    upload_mock.reset_mock()

    assert Media(project=project, report=report).model_dump() == {
        "content_type": content_type,
        "name": accessor,
        "data_source": data_source,
        "checksum": None,
    }

    # ensure `upload` is not called
    assert not upload_mock.called

    # wrong type
    with raises(
        ValidationError,
        match=f"Input should be an instance of {report.__class__.__name__}",
    ):
        Media(project=project, report=None)
