from io import BytesIO

from matplotlib import pyplot as plt
from pydantic import ValidationError
from pytest import mark, param, raises

from skore_hub_project.artifact.media import (
    PrecisionRecallSVGTest,
    PrecisionRecallSVGTrain,
    PredictionErrorSVGTest,
    PredictionErrorSVGTrain,
    RocSVGTest,
    RocSVGTrain,
)
from skore_hub_project.artifact.serializer import Serializer


def serialize(display) -> bytes:
    with BytesIO() as stream:
        display.plot()
        display.figure_.savefig(stream, format="svg", bbox_inches="tight")
        plt.close(display.figure_)

        figure_bytes = stream.getvalue()

    return figure_bytes


@mark.filterwarnings(
    # ignore deprecation warnings generated by the way `pandas` is used by `searborn`,
    # which is a dependency of `skore`
    "ignore:The default of observed=False is deprecated.*:FutureWarning:seaborn",
)
@mark.parametrize(
    "Media,report,accessor,data_source",
    (
        param(
            PrecisionRecallSVGTest,
            "binary_classification",
            "precision_recall",
            "test",
            id="PrecisionRecallSVGTest[estimator]",
        ),
        param(
            PrecisionRecallSVGTrain,
            "binary_classification",
            "precision_recall",
            "train",
            id="PrecisionRecallSVGTrain[estimator]",
        ),
        param(
            PrecisionRecallSVGTest,
            "cv_binary_classification",
            "precision_recall",
            "test",
            id="PrecisionRecallSVGTest[cross-validation]",
        ),
        param(
            PrecisionRecallSVGTrain,
            "cv_binary_classification",
            "precision_recall",
            "train",
            id="PrecisionRecallSVGTrain[cross-validation]",
        ),
        param(
            PredictionErrorSVGTest,
            "regression",
            "prediction_error",
            "test",
            id="PredictionErrorSVGTest[estimator]",
        ),
        param(
            PredictionErrorSVGTrain,
            "regression",
            "prediction_error",
            "train",
            id="PredictionErrorSVGTrain[estimator]",
        ),
        param(
            PredictionErrorSVGTest,
            "cv_regression",
            "prediction_error",
            "test",
            id="PredictionErrorSVGTest[cross-validation]",
        ),
        param(
            PredictionErrorSVGTrain,
            "cv_regression",
            "prediction_error",
            "train",
            id="PredictionErrorSVGTrain[cross-validation]",
        ),
        param(
            RocSVGTest,
            "binary_classification",
            "roc",
            "test",
            id="RocSVGTest[estimator]",
        ),
        param(
            RocSVGTrain,
            "binary_classification",
            "roc",
            "train",
            id="RocSVGTrain[estimator]",
        ),
        param(
            RocSVGTest,
            "cv_binary_classification",
            "roc",
            "test",
            id="RocSVGTest[cross-validation]",
        ),
        param(
            RocSVGTrain,
            "cv_binary_classification",
            "roc",
            "train",
            id="RocSVGTrain[cross-validation]",
        ),
    ),
)
@mark.respx()
def test_performance(
    monkeypatch,
    Media,
    report,
    accessor,
    data_source,
    upload_mock,
    request,
    project,
):
    report = request.getfixturevalue(report)
    display = getattr(report.metrics, accessor)(data_source=data_source)
    content = serialize(display)

    with Serializer(content) as serializer:
        checksum = serializer.checksum

    # available accessor
    assert Media(project=project, report=report).model_dump() == {
        "content_type": "image/svg+xml",
        "name": accessor,
        "data_source": data_source,
        "checksum": checksum,
    }

    # ensure `upload` is well called
    assert upload_mock.called
    assert not upload_mock.call_args.args
    assert upload_mock.call_args.kwargs == {
        "project": project,
        "content": content,
        "content_type": "image/svg+xml",
    }

    # unavailable accessor
    monkeypatch.delattr(report.metrics.__class__, accessor)
    upload_mock.reset_mock()

    assert Media(project=project, report=report).model_dump() == {
        "content_type": "image/svg+xml",
        "name": accessor,
        "data_source": data_source,
        "checksum": None,
    }

    # ensure `upload` is not called
    assert not upload_mock.called

    # wrong type
    with raises(
        ValidationError,
        match=f"Input should be an instance of {report.__class__.__name__}",
    ):
        Media(project=project, report=None)
