class TestProject:
    def test_init_local(self): ...

    def test_init_remote(self): ...

    def test_init_exception(self): ...

    def test_put(self): ...

    def test_put_exception(self): ...

    def test_reports(self): ...

    def test_reports_get(self): ...

    def test_reports_metadata(self): ...
