# THIS
# IS
# DOCUMENTATION
# REUSABLE WORKFLOW

name: Backend

on: [workflow_call]

defaults:
  run:
    shell: "bash"

jobs:
  test-skore:
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python: ["3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
      - name: Setup
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pre-commit
          python -m pip install --upgrade build
      - name: Lint
        working-directory: skore/
        run: pre-commit run --all-files ruff
      - name: Build
        working-directory: skore/
        run: python -m build
      - name: Install
        working-directory: skore/
        run: wheel=(dist/*.whl); python -m pip install "${wheel}[test]"
      - name: Test without coverage
        if: matrix.os != 'ubuntu-latest' ||  matrix.python != '3.12'
        timeout-minutes: 10
        working-directory: skore/
        run: python -m pytest --no-cov src/ tests/
      - name: Test with coverage
        if: matrix.os == 'ubuntu-latest' && matrix.python == '3.12'
        timeout-minutes: 10
        working-directory: skore/
        run: |
          mkdir coverage
          python -m pytest --junitxml=coverage/coverage.xml --cov=skore src/ tests/ | tee coverage/coverage.txt
      - name: Upload coverage reports
        if: matrix.os == 'ubuntu-latest' && matrix.python == '3.12'
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: skore/coverage/
