# THIS
# IS
# DOCUMENTATION

name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      skore: ${{ steps.filter.outputs.skore }}
      skore-ui: ${{ steps.filter.outputs.skore-ui }}
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            skore:
              - 'skore/src/**'
              - 'skore/tests/**'
              - 'skore/pyproject.toml'
              - 'skore/requirements*.txt'
              - '.github/workflows/backend.yml'
            skore-ui:
              - 'skore-ui/**'
              - '.github/workflows/frontend.yml'

  lint-all-files:
    uses: ./.github/workflows/lint.yml
    permissions:
      contents: read

  lint-and-test-backend:
    needs: [lint-all-files, changes]
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'pull_request' && needs.changes.outputs.skore == 'true')
    uses: ./.github/workflows/backend.yml
    permissions:
      contents: read

  lint-and-test-frontend:
    needs: [lint-all-files, changes]
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'pull_request' && needs.changes.outputs.skore-ui == 'true')
    uses: ./.github/workflows/frontend.yml
    permissions:
      contents: read

  ci-all-green:
    needs:
      - changes
      - lint-all-files
      - lint-and-test-backend
      - lint-and-test-frontend
    if: always()
    runs-on: Ubuntu-latest
    steps:
      - shell: bash
        run: |
          [[  ${{ contains(needs.*.result, 'failure') }} = false ]]
