name: ci

on:
  pull_request:
  push:
    branches:
      - main
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            backend:
              - '.github/workflows/backend.yml'
              - 'skore/**'

  lint:
    uses: ./.github/workflows/lint.yml
    permissions:
      contents: read

  backend:
    needs: [lint, changes]
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || (contains(fromJSON('["pull_request", "merge_group"]'), github.event_name) && needs.changes.outputs.backend == 'true') }}
    uses: ./.github/workflows/backend.yml
    permissions:
      contents: read

  ci-all-green:
    needs:
      - changes
      - lint
      - backend
    if: ${{ always() }}
    runs-on: Ubuntu-latest
    steps:
      - shell: bash
        run: |
          [[  ${{ contains(needs.*.result, 'failure') }} = false ]]
