name: CI

on: [pull_request]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      skore-ui: ${{ steps.filter.outputs.skore-ui }}
    permissions:
      pull-requests: read
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'src/**'
              - 'tests/**'
              - 'pyproject.toml'
              - 'requirements*.txt'
              - '.github/workflows/backend.yml'
            skore-ui:
              - 'skore-ui/**'
              - '.github/workflows/skore-ui.yml'

  lint-all-files:
    uses: ./.github/workflows/lint.yml
    permissions:
      contents: read

  lint-and-test-backend:
    needs: [lint-all-files, changes]
    if: ${{ needs.changes.outputs.backend == 'true' }}
    uses: ./.github/workflows/backend.yml
    permissions:
      contents: read

  lint-and-test-skore-ui:
    needs: [lint-all-files, changes]
    if: ${{ needs.changes.outputs.skore-ui == 'true' }}
    uses: ./.github/workflows/skore-ui.yml
    permissions:
      contents: read
      pull-requests: write

  ci-all-green:
    needs:
      - lint-all-files
      - lint-and-test-backend
      - lint-and-test-skore-ui
    if: ${{ always() }}
    runs-on: Ubuntu-latest
    steps:
      - shell: bash
        run: |
          [[  ${{ contains(needs.*.result, 'failure') }} = false ]]
