# THIS
# IS
# DOCUMENTATION
# REUSABLE WORKFLOW

name: Frontend

on: [workflow_call]

defaults:
  run:
    shell: 'bash'

jobs:
  lint-skore-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: skore-ui/package-lock.json
      - name: Lint skore-ui
        working-directory: skore-ui/
        run: |
          npm install
          npm run type-check
          npm run lint
          npm run format
          npm run style-lint

  test-skore-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: skore-ui/package-lock.json
      - name: Test skore-ui
        working-directory: skore-ui/
        run: |
          npm install
          npm run test:unit:coverage
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: skore-ui/coverage/

  build-skore-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: skore-ui/package-lock.json
      - name: Build skore-ui
        working-directory: skore-ui/
        run: |
          npm install
          npm run build
