name: Lint and test backend

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - pyproject.toml
      - Makefile
      - requirements*.txt
      - .pre-commit-config.yaml

permissions:
  contents: read

jobs:
  lint-and-test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e . -r requirements.txt -r requirements-test.txt
      - name: Build frontend and share library
        shell: bash
        run: make build-frontend

      - name: Lint src/ with pre-commit
        run: |
          cd src/
          pre-commit run --all-files
      - name: Lint tests/ with pre-commit
        run: |
          cd tests/
          pre-commit run --all-files
      - name: Test with pytest
        timeout-minutes: 5
        run: |
          python -m pytest
