name: lint

on:
  pull_request:
  push:
    branches:
      - main
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: "bash"

env:
  PIXI_VERSION: v0.69.0
  PIXI_ENV: lint

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
        with:
          pixi-version: ${{ env.PIXI_VERSION }}
          environments: ${{ env.PIXI_ENV }}
          cache: true
          locked: true

      - name: Lint
        run: pixi run -e ${{ env.PIXI_ENV }} lint
