name: send backend coverage

on:
  workflow_run:
    workflows: [Reusable skore workflow]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  send-coverage-message:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          name: backend-coverage
          path: coverage/
      - name: Send
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: coverage/coverage.txt
          junitxml-path: coverage/coverage.xml
          title: pytest coverage report
