name: pr-serve-documentation-preview

on:
  workflow_run:
    workflows: [sphinx]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  pr-serve-documentation-preview:
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      actions: read
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: .github

      - name: Download HTML artifacts
        id: download-html-artifacts
        continue-on-error: True
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: sphinx-html-artifact
          path: html/
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Acquire PR context
        if: ${{ steps.download-html-artifacts.outcome == 'success' }}
        id: acquire-pr-context
        uses: ./.github/actions/workflow-run/context

      - name: Serve documentation preview
        if: ${{ steps.download-html-artifacts.outcome == 'success' }}
        uses: ./.github/actions/sphinx/deploy-aws
        with:
          BUCKET: ${{ vars.DOCUMENTATION_PREVIEW_BUCKET }}
          ACL: public-read
          ROLE_TO_ASSUME: ${{ vars.AWS_ROLE }}
          SOURCE: html/
          DESTINATION: ${{ steps.acquire-pr-context.outputs.pr-number }}/

      - name: Comment with documentation preview link
        if: ${{ steps.download-html-artifacts.outcome == 'success' }}
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        with:
          number: ${{ steps.acquire-pr-context.outputs.pr-number }}
          header: documentation-preview
          message: >-
            [Documentation preview](${{ vars.DOCUMENTATION_PREVIEW_URL }}/${{ steps.acquire-pr-context.outputs.pr-number }})
            @ ${{ steps.acquire-pr-context.outputs.pr-head-sha }}
