# Adapted from https://github.com/soda-inria/hazardous/blob/main/.github/workflows/push_doc.yml
name: Build documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  push_doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install .[doc]

      - name: Sphinx build
        run: sphinx-build doc build

      - name: Save the PR number
        env:
          GITHUB_PULL_REQUEST_NUMBER: ${{github.event.number}}
        run: |
          echo "Storing PR number ${{github.event.number}} to 'pull_request_number' file"
          echo ${{github.event.number}} > pull_request_number

      - name: Upload doc preview
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: doc-preview
          path: |
            ./build
            pull_request_number
