on:
  pull_request:
    types: [opened]


jobs:
  add-assignee:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - shell: bash
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${REPOSITORY_OWNER}/${REPOSITORY_NAME}/issues/${PULL_REQUEST_NUMBER}/assignees \
            -f "assignees[]=${USERNAME}"
        env:
          GH_TOKEN: ${{ github.token }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
          USERNAME: ${{ github.event.sender.login }}
