name: Test frontend

on:
  push:
    paths:
      - 'frontend/**'
      - .github/workflows/test-frontend.yml

permissions:
  contents: read
  pull-requests: write

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build frontend and share library
        shell: bash
        run: make build-frontend

      - name: Vitest
        run: |
          cd frontend
          npm run test:unit:coverage

      - uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - name: Report coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: ./frontend
          pr-number: ${{ steps.findPr.outputs.pr }}
