name: Test backend

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - pyproject.toml
      - Makefile
      - requirements*.txt
      - .github/workflows/test-backend.yml

permissions:
  contents: read

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build frontend and share library
        shell: bash
        run: make build-frontend

      - name: Build package distributions
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m build

      - name: Install
        run: |
          python -m pip install dist/*.whl --no-dependencies
          python -m pip install -r requirements.txt -r requirements-test.txt

      - name: Pytest
        timeout-minutes: 5
        run: python -m pytest
